name: Run API and UI Tests

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore NuGet packages
        run: dotnet restore

      - name: Build the solution
        run: dotnet build --configuration Release --no-restore

      - name: Restore tools and install Playwright
        run: |
          dotnet tool restore
          dotnet playwright install --with-deps

      - name: Run tests and collect results
        run: |
          dotnet test PreservicaDemo/PreservicaDemo.csproj \
            --configuration Release \
            --no-build \
            --logger "trx;LogFileName=test-results.trx"
        continue-on-error: true

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: '**/test-results.trx'
