name: Run API and UI Tests

on:
  push:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --configuration Release --no-restore

      - name: Install Playwright CLI and Browsers
        run: |
          dotnet tool install --global Microsoft.Playwright.CLI
          dotnet playwright install --with-deps

      - name: Run Tests (Headless)
        run: dotnet test --configuration Release --no-build --logger "console;verbosity=detailed"
